services:
  blinkstickscheduler:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TZ: "America/Los_Angeles"
    #volumes:
    #  - /dev/bus/usb/:/dev/bus/usb
    privileged: true
    restart: unless-stopped
