services:
  blinkstickscheduler:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TZ: America/Los_Angeles
    privileged: true
    restart: unless-stopped
networks: {}
